#
# Module manifest for module 'Attach-With'
#
# Generated by: Ibne Nahian (evilprince2009)
#
# Generated on: 19-Jan-24
#

@{

    # Version number of this module.
    ModuleVersion = '1.0'

    # Script module or binary module file associated with this manifest.
    RootModule = 'attach-with.psm1'

    # ID used to uniquely identify this module
    GUID = '172bfb35-fd6c-41c6-9d88-f884c9317699'

    # Company or vendor of this module
    CompanyName = 'Unknown'

    # Author of this module
    Author = 'Ibne Nahian'

    # Copyright statement for this module
    Copyright = '(c) 2024 Ibne Nahian'

    # Description of the functionality provided by this module
    Description = 'A PowerShell module for command prefixing'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # List of all files packaged with this module
    FileList = @()

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = '*'

    # Functions to export from this module
    FunctionsToExport = @('Start-With', 'Write-WithPrompt')

    # Private data to pass to the module specified in RootModule. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('git', 'with', 'repeat', 'bash', 'prompt')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/evilprince2009/Attach-With/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/evilprince2009/Attach-With'

        } # End of PSData hashtable
    } # End of PrivateData hashtable
}

